### PR TITLE
Add @GetAll for list dependencies. Fixes gh-37

### PR DESCRIPTION
**Pull request by PaulWMR**
If a parameter is of type List, the default behaviour is to fill it with get(). Sometimes a getAll() is required instead. @GetAll provides this possibility.

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Interesting proposal. Still wondering if we call it `@GetAll`, but seems right in the usage 🤔

**Comment by arnaudgiuliani** [comment]
No real other. proposal to change `@GetAll` for now 🤔  It follows up well with existing

**Comment by PaulWMR** [comment]
I've just adjusted my commits (i.e. overwritten them) to ensure they are all signed. I hope this PR will soon be merged and released so this functionality can be used pretty soon. It would be very useful for some of my projects :-)

**Comment by iota9star** [comment]
Any updates?

**Comment by arnaudgiuliani** [comment]
I will manage to merge it

**Comment by arnaudgiuliani** [comment]
After some thinking around, I believe that injecting a `List<A>` has more meaning by generating directly `getAll()`.  Let's try like that without annotation: 5ae267527883be51ce7e7b5d53ff245e60682fa3

Else we will reopen this proposal 👍

**Pull request closed without merging**
