### PR TITLE
fix: Removed "it" from forbiddenKeywords and replace "" with "_ -> " …

### PR DESCRIPTION
**Pull request by FCatinella**
Adding back ticks  to "it" causes problems when ksp tries to generate variable names when package names start with "it", hence the removal from `forbiddenKeywords`.

We ([samuelepozzebon](https://github.com/samuelepozzebon) and I) also changed `""` to `"_ -> "` in order to fix the issue "it" creates since it is used as the default param name.

For example:
`single() {  'it'.example.italy.classProvider() }...`
become
`single() { _ -> it.example.italy.classProvider() }...`

This PR fixes: https://github.com/InsertKoinIO/koin-annotations/issues/161

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Ok, looking at it

**Comment by arnaudgiuliani** [comment]
>We ([samuelepozzebon](https://github.com/samuelepozzebon) and I) also changed "" to "_ -> " in order to fix the issue "it" creates since it is used as the default param name.

I don't see the problem in that case? We don't use `it` on generated code definition 🤔 

Can you add a test case?

**Comment by FCatinella** [comment]
Hi! Sorry for not being clear. What I meant is that Lambas in Kotlin use "it" as default parameter name when not specified.
Hence the explicit parameters declaration "_ ->" instead of ""

Btw, I'll add a test case asap.
Thanks for your time

**Comment by arnaudgiuliani** [comment]
I'll merge your PR and add somethign simple to test 👍

**Comment by arnaudgiuliani** [comment]
thanks @FCatinella

**Comment by FCatinella** [comment]
Thanks to you @arnaudgiuliani

**Pull request merged**
