### PR TITLE
fix: check safety issue for providing SavedStateHandle & Context

### PR DESCRIPTION
**Pull request by ghasemdev**

### CODE REVIEW

**Comment by ghasemdev** [comment]
@arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
Good addition. Can you add a sample test in the sandbox app? Otherwise I will manage to add it later ... but would be great to make it complete.

**Comment by ghasemdev** [comment]
> Good addition. Can you add a sample test in the sandbox app? Otherwise I will manage to add it later ... but would be great to make it complete.

I tried to build the Sandbox project but was unsuccessful. I feel that the Gradle dependencies were outdated. I am using the latest version of Android Studio, which requires Gradle and plugin version 8.2.

**Comment by ghasemdev** [comment]
Also, I made the changes on my local and got the output, then tested it on my sample project and it worked.

https://github.com/ghasemdev/sample-koin-project

**Comment by ghasemdev** [comment]
## Before
image

## After
image

**Comment by arnaudgiuliani** [comment]
Thanks for your contribution 👍

**Pull request merged**
