### PR TITLE
Fix source set configuration

### PR DESCRIPTION
**Pull request by ugurcany**
Using `configureEach` instead of `all` is much better. It's not required to clean project between flavor changes anymore.

### CODE REVIEW

**Comment by javichaques** [comment]
Thanks @ugurcany for solution :)

**Comment by hblockx** [comment]
pls merge it :)

**Comment by hblockx** [comment]
Anyone here maintaining Koin Annotations?

**Comment by arnaudgiuliani** [comment]
yes, be patient 👍

**Comment by kazemcodes** [comment]
what is the equal code for Gradle Kotlin DSL?
```
android {
  applicationVariants.all { variant ->
          variant.sourceSets.java.each {
              it.srcDirs += "build/generated/ksp/${variant.name}/kotlin"
          }
      }
}
```

**Review by arnaudgiuliani — APPROVED** [review]

**Comment by AdamHavlicek** [comment]
should docs [Gradle Setup](https://insert-koin.io/docs/quickstart/android-annotations/#gradle-setup) be updated as well?

**Pull request merged**
